version: '3.7'
services:
  consolidationlogs:
    container_name: consolidationlogs
    image: yizimaw/consolidation_metrics_access_app:v01A
    restart: always
    ports:
      - '3033:3033'
    environment:
      - DBPOSTGRES_HOST=37.60.247.1
      - DBPOSTGRES_USER=root
      - DBPOSTGRES_PASS=ZdGXaUHeZ3EKafasfasfaszU=dasdasdsa
      - DBPOSTGRES_DATABASE=VYZ
      - PORT=3034

    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.consolidationlogs.rule=Host(`consolidationlogs.vyzolutions.com.br`)'
      - 'traefik.http.routers.consolidationlogs.entrypoints=websecure'
      - 'traefik.http.routers.consolidationlogs.tls.certresolver=leresolver'
      - 'traefik.http.services.consolidationlogs.loadbalancer.server.port=3033'
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
